import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'de' | 'en';

interface SettingsState {
  volume: number;
  fxVolume: number;
  language: Language;
  setVolume: (v: number) => void;
  setFxVolume: (v: number) => void;
  setLanguage: (l: Language) => void;
}

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set) => ({
      volume: 2,
      fxVolume: 10,
      language: 'de',
      setVolume: (v) => set({ volume: Math.max(0, Math.min(100, v)) }),
      setFxVolume: (v) => set({ fxVolume: Math.max(0, Math.min(100, v)) }),
      setLanguage: (l) => set({ language: l }),
    }),
    { name: 'quest-forge-settings' }
  )
);

export const TRANSLATIONS = {
  de: {
    settings: 'Einstellungen',
    language: 'Sprache',
    german: 'Deutsch',
    english: 'Englisch',
    volume: 'Lautstärke',
    soundEffects: 'Soundeffekte',
    music: 'Musik',
    close: 'Schließen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    teleport: 'Teleport',
    teleportCost: 'Teleport-Kosten',
    notEnoughGold: 'Nicht genug Gold!',
    level: 'Level',
    required: 'Benötigt',
    locked: 'Gesperrt',
    clickToTalk: 'Klick zum Sprechen',
    quests: 'AUFTRÄGE',
    saveGame: 'Spiel gespeichert!',
    levelUp: 'LEVEL UP!',
    skillPointsAvailable: 'Skill-Punkte verfügbar!',
    warrior: 'Krieger',
    mage: 'Magier',
    archer: 'Bogenschütze',
    hp: 'HP',
    mp: 'MP',
    xp: 'XP',
    attack: 'Angriff',
    defense: 'Verteidigung',
    gold: 'Gold',
    inventory: 'Inventar',
    skills: 'Fähigkeiten',
    party: 'Gruppe',
    shop: 'Händler',
    pets: 'Haustiere',
    hub: 'ZUM HUB',
    respawn: 'RESPAWN',
    toHub: 'ZUM HUB',
    zoneCleared: 'Zone Gesäubert!',
    allEnemiesDefeated: 'Alle Gegner besiegt!',
    defeated: 'Besiegt!',
    youWereDefeated: 'Du wurdest besiegt...',
    restart: 'NEUSTART',
    move: 'Bewegen',
    useSkill: 'Skill',
    openInventory: 'Inventar',
    openSkills: 'Fähigkeiten',
    openParty: 'Gruppe',
    teleportNPC: 'Blinkstein-Händler',
    clickToTeleport: 'Klick zum Teleportieren',
    requiredLevel: 'Lv.',
    classSelect: 'Wähle deine Klasse',
    selectClass: 'Wähle deine Klasse',
    startGame: 'Spiel starten',
    blacksmith: 'Schmied',
    merchant: 'Händler',
    petMaster: 'Pet-Meisterin',
    rebirthAltar: 'Rebirth-Altar',
    questAvailable: 'Verfügbar',
    questActive: 'Aktiv',
    questCompleted: 'Abgeschlossen',
    accept: 'Annehmen',
    complete: 'Abschließen',
    buy: 'Kaufen',
    sell: 'Verkaufen',
    equip: 'Ausrüsten',
    unequip: 'Ausziehen',
    use: 'Benutzen',
    price: 'Preis',
    owned: 'Besitzt',
    equipped: 'Ausgerüstet',
    damage: 'Schaden',
    healing: 'Heilung',
    experience: 'Erfahrung',
    critical: 'Kritisch!',
    noGold: 'Nicht genug Gold!',
    petBonus: 'Bonus',
    autoFight: 'Auto-Kampf',
    autoRespawn: 'Auto-Respawn',
    autoOn: 'AN',
    autoOff: 'AUS',
  },
  en: {
    settings: 'Settings',
    language: 'Language',
    german: 'German',
    english: 'English',
    volume: 'Volume',
    soundEffects: 'Sound Effects',
    music: 'Music',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    teleport: 'Teleport',
    teleportCost: 'Teleport Cost',
    notEnoughGold: 'Not enough gold!',
    level: 'Level',
    required: 'Required',
    locked: 'Locked',
    clickToTalk: 'Click to talk',
    quests: 'QUESTS',
    saveGame: 'Game saved!',
    levelUp: 'LEVEL UP!',
    skillPointsAvailable: 'Skill points available!',
    warrior: 'Warrior',
    mage: 'Mage',
    archer: 'Archer',
    hp: 'HP',
    mp: 'MP',
    xp: 'XP',
    attack: 'Attack',
    defense: 'Defense',
    gold: 'Gold',
    inventory: 'Inventory',
    skills: 'Skills',
    party: 'Party',
    shop: 'Shop',
    pets: 'Pets',
    hub: 'TO HUB',
    respawn: 'RESPAWN',
    toHub: 'TO HUB',
    zoneCleared: 'Zone Cleared!',
    allEnemiesDefeated: 'All enemies defeated!',
    defeated: 'Defeated!',
    youWereDefeated: 'You have been defeated...',
    restart: 'RESTART',
    move: 'Move',
    useSkill: 'Skill',
    openInventory: 'Inventory',
    openSkills: 'Skills',
    openParty: 'Party',
    teleportNPC: 'Blinkstone Merchant',
    clickToTeleport: 'Click to teleport',
    requiredLevel: 'Lv.',
    classSelect: 'Choose your class',
    selectClass: 'Choose your class',
    startGame: 'Start Game',
    blacksmith: 'Blacksmith',
    merchant: 'Merchant',
    petMaster: 'Pet Master',
    rebirthAltar: 'Rebirth Altar',
    questAvailable: 'Available',
    questActive: 'Active',
    questCompleted: 'Completed',
    accept: 'Accept',
    complete: 'Complete',
    buy: 'Buy',
    sell: 'Sell',
    equip: 'Equip',
    unequip: 'Unequip',
    use: 'Use',
    price: 'Price',
    owned: 'Owned',
    equipped: 'Equipped',
    damage: 'Damage',
    healing: 'Healing',
    experience: 'Experience',
    critical: 'Critical!',
    noGold: 'Not enough gold!',
    petBonus: 'Bonus',
    autoFight: 'Auto-Fight',
    autoRespawn: 'Auto-Respawn',
    autoOn: 'ON',
    autoOff: 'OFF',
  },
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.de;

export function t(key: TranslationKey): string {
  const lang = useSettingsStore.getState().language;
  return TRANSLATIONS[lang][key] || key;
}

export function useTranslation() {
  const language = useSettingsStore(s => s.language);
  return (key: TranslationKey): string => TRANSLATIONS[language][key] || key;
}
